config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'
  get 'categories/new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'homes/parsing_data'
  
  get 'clients/new'
  post 'clients/create'
  get 'clients/index'

  get 'parts/show/:id', to: 'parts#show', as: :parts_show
  get 'parts/index'
  get 'parts/new'
  post 'parts/create'

  root to: "homes#welcome"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= AdminUser.new
    if user.admin_roles.map{|m| m.superadmin? }.first
      can :manage, :all
    elsif user.admin_roles.map{|m| m.admin? }.first
      can :read, :update, :all 
    else
      can :read, :all
    end
  end
end

app/models/admin_role.rb
class AdminRole < ApplicationRecord
  
  has_and_belongs_to_many :admin_users

  enum role_type:[:user,:admin,:superadmin]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :admin_roles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  has_and_belongs_to_many :parts
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :student
  validates :description,  presence: true 
end

app/models/category.rb
class Category < ApplicationRecord
  after_save :clear_cache

  def clear_cache
    $redis.del "categories"
  end
  
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :projects
  has_many :programmers, through: :projects
  accepts_nested_attributes_for :projects
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
  accepts_nested_attributes_for :assemblies
end

app/models/programmer.rb
class Programmer < ApplicationRecord
  has_many :projects
  has_many :clients, through: :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :programmer
  belongs_to :client
  accepts_nested_attributes_for :programmer
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :books
  validates :name, :roll_number, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper

  def index
    @categories = fetch_categories
  end

  def new
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all 
  end

  def new
    @client = Client.new 
    @projects = @client.projects.build
    @programmer = @projects.build_programmer 
  end

  def create
    client = Client.new(client_params)
    if client.save
      redirect_to root_path
    else 
      redirect_to clients_new_path
    end
  end

  private
  def client_params
    params.require(:client).permit(:id, :name, projects_attributes: [:id, :project_date, programmer_attributes: [:id, :name ]] )
  end
end

app/controllers/homes_controller.rb
require 'nokogiri'
require 'open-uri'

class HomesController < ApplicationController
  def welcome 
  end 

  def parsing_data
    doc = Nokogiri::HTML(URI.open('https://nokogiri.org/tutorials/installing_nokogiri.html'))
    @supported_platform = doc.css('article ul li')[1..4]
    @native_gem_details = doc.xpath('//article//p')[8..10]
    @nokogiri_support = doc.search('nav ul li', '//label//a')
  end 

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  def index
    @parts = Part.all
  end

  def show
    @part = Part.find(params[:id])
  end

  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to parts_index_path
    else 
      redirect_to parts_new_path
    end
  end

  def new
    @part = Part.new
    @assemblies = @part.assemblies.build
  end

  private
  def part_params
    params.require(:part).permit(:id, :part_number, :part_name, assemblies_attributes: [:id, :name] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def fetch_categories
    categories =  $redis.get("categories")
    if categories.nil?
      categories = Category.all.to_json
      $redis.set("categories", categories)
      # Expire the cache, every 200 seconds.
      $redis.expire("categories", 200.seconds.to_i)
    end
    @categories = JSON.load categories
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/categories/index.html.haml
%h1 Category Listing
%ul
  - @categories.each do |category|
    %li
      Description: #{category["description"]} Name: #{category["name"]}

app/views/categories/new.html.haml
%h1 Category#new
%p Find me in app/views/category/new.html.erb

app/views/clients/index.html.erb
<h1 class="heading">List of all clients</h1>
<table>
  <thead>
    <tr> 
      <th> Client Name</th> 
      <th> Client Project Date</th>
      <th> Client's Assigned Programmers</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td>
           <%= client.name %> 
        </td>
        <td>
          <% client.projects.each do |project| %>
            <%= project.project_date %> 
          <% end %>
        </td>
        <td>
          <% client.programmers.each do |programmer| %>
            <%= programmer.name %> 
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<%= form_for @client, url: clients_create_path(@client) do |client_form| %>
  <p>
    <%= client_form.label :name, "client Name" %>
    <%= client_form.text_field :name %>
  </p>

  <%= client_form.fields_for :projects do |project_form| %>
    <p>
      <%= project_form.label :project_date, "Project Date" %>
      <%= project_form.date_field :project_date %>
    </p>

    <%= project_form.fields_for :programmer do |programmer_form| %>
      <p>
        <%= programmer_form.label :name, "Programmer Name" %>
        <%= programmer_form.text_field :name %>
      </p>
    <% end %>
  <% end %>

  <p>
    <%= client_form.submit 'Create' %>
  </p>
<% end %>
<%= link_to 'Back', clients_new_path %>

app/views/parts/index.html.erb
<h1 class="heading">List of all parts</h1>
<table>
  <thead>
    <tr> 
      <th> Part Name</th> 
      <th> Part Number</th>
      <th> Part's Assemblies</th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td>
           <%= part.part_name %> 
        </td>
        <td>
           <%= part.part_number %> 
        </td>
        <td>
          <%= part.assemblies.pluck(:name).join(',') %>
        </td>
        <td>
          <%= link_to 'Show', parts_show_path(part) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parts/new.html.erb
<%= form_for @part, url: parts_create_path(@part) do |part_form| %>
  <p>
    <%= part_form.label :part_name, "Part Name" %>
    <%= part_form.text_field :part_name %>
  </p>
  <p>
    <%= part_form.label :part_number, "Part Number" %>
    <%= part_form.text_field :part_number %>
  </p>

  <%= part_form.fields_for :assemblies do |assembly_form| %>
    <p>
      <%= assembly_form.label :name, "Assembly Name" %>
      <%= assembly_form.text_field :name %>
    </p>
  <% end %>

  <p>
    <%= part_form.submit 'Create' %>
  </p>
<% end %>
<%= link_to 'Back', parts_new_path %>

app/views/parts/show.html.erb
<h1>Parts who have the <%= @part.part_name %> part name with part no. <%= @part.part_number %></h1>
<ul>
  <% @part.assemblies.each do |assembly| %>
    <li><%= assembly.name %></li>
  <% end %>
</ul>